# public/admin/config.yml
backend:
  name: git-gateway
  branch: main # The branch to update
  repo: huynhlan.fe/my-nextjs-cms

local_backend: true
# set to true to allow decap cms to save file locally during development

media_folder: "public/uploads" # Folder to store media
public_folder: "/uploads" # Public URL for media

# Here we define content structure
collections:
  - label: "Home page"
    name: "homepage"
    files:
      - label: "Hero"
        name: "hero"
        file: "app/content/hero.md" # Path to the markdown file
        create: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
              required: false,
            }
          - { label: "Button Text", name: "buttonText", widget: "string" }
